name: Generate Android Signing Key

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore release-key.jks \
            -alias release \
            -keyalg RSA \
            -keysize 2048 \
            -validity 36525 \
            -storepass "123456" \
            -keypass "123456" \
            -dname "CN=MyApp, OU=Android, O=MyCompany, L=New York, ST=New York, C=US"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: android-signing-key
          path: release-key.jks