name: Delete files

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Delete files
        run: |

      - name: Commit
        run: |
          git config user.name "DarkCode2317"
          git config user.email "darkcode2317@gmail.com"
          git add .
          git commit -m "Delete files"
          git push
        